/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import StudentIsA.GraduateStudent;
import SystemClassesAndMain.StudentSys;
import java.awt.event.KeyEvent;

/**
 *
 * @author Aizaz Hassan<Aizaz.Hassan>
 */
public class GraduateStudentFrame extends javax.swing.JFrame {

    /**
     * Creates new form GraduateStudentFrame
     */
    MainFrame mf;
    public GraduateStudentFrame(MainFrame mf) {
        initComponents();
        this.mf=mf;
    }

    public void clear() {
        txtId.setText("");
        txtName.setText("");
        checkBoxTheory.setSelected(false);
        txtSurname.setText("");
        txtYearOfAdmission.setText("");
        txtYear.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtYearOfAdmission = new javax.swing.JTextField();
        txtSurname = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtYear = new javax.swing.JTextField();
        labelAlert = new javax.swing.JLabel();
        btnAddCourses = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        checkBoxTheory = new javax.swing.JCheckBox();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add Graduate Student");

        jLabel1.setText("Student ID:");

        jLabel2.setText("Name:");

        jLabel3.setText("Surname:");

        jLabel4.setText("Year of Admission:");

        jLabel6.setText("Year Number:");

        txtYear.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtYearKeyPressed(evt);
            }
        });

        btnAddCourses.setText("ADD COURSES");
        btnAddCourses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddCoursesActionPerformed(evt);
            }
        });

        btnClose.setText("CLOSE");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        checkBoxTheory.setText("Done");

        jLabel7.setText("Thesis:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(labelAlert, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel6))
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtYearOfAdmission)
                                .addComponent(txtSurname)
                                .addComponent(txtName)
                                .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                                .addComponent(txtYear)
                                .addComponent(checkBoxTheory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAddCourses, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSurname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtYearOfAdmission, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(checkBoxTheory)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtYear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelAlert, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddCourses)
                    .addComponent(btnClose))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddCoursesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddCoursesActionPerformed
        if (txtId.getText().isEmpty() || txtName.getText().isEmpty() || txtYear.getText().isEmpty()
                || txtSurname.getText().isEmpty() || txtYearOfAdmission.getText().isEmpty()
                || txtYear.getText().isEmpty()) {
            labelAlert.setText("Please fill all the fields!");
        } else {
            if (StudentSys.searchStudent(Integer.parseInt(txtId.getText())) != null) {
                labelAlert.setText("Student already exists!");
            } else {
                GraduateStudent g = new GraduateStudent(txtId.getText(),
                        txtName.getText(), txtSurname.getText(), txtYearOfAdmission.getText(),
                        checkBoxTheory.isSelected()?"Completed":"Not Completed", txtYear.getText());
                StudentSys.addStudent(g);
                AddStudentCoursesFrame courseFrame = new AddStudentCoursesFrame(g, this);
                courseFrame.setVisible(true);
                setVisible(false);
                labelAlert.setText(txtName.getText() + " " + txtSurname.getText() + " is added");
                clear();
            }
        }
    }//GEN-LAST:event_btnAddCoursesActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        dispose();
        mf.setVisible(true);
    }//GEN-LAST:event_btnCloseActionPerformed

    private void txtYearKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtYearKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (txtId.getText().isEmpty() || txtName.getText().isEmpty() || txtYear.getText().isEmpty()
                    || txtSurname.getText().isEmpty() || txtYearOfAdmission.getText().isEmpty()
                    || txtYear.getText().isEmpty()) {
                labelAlert.setText("Please fill all the fields!");
            } else {
                if (StudentSys.searchStudent(Integer.parseInt(txtId.getText())) != null) {
                    labelAlert.setText("Student already exists!");
                } else {
                    GraduateStudent g = new GraduateStudent(txtId.getText(),
                            txtName.getText(), txtSurname.getText(), txtYearOfAdmission.getText(),
                            checkBoxTheory.isSelected()?"Completed":"Not Completed", txtYear.getText());
                    StudentSys.addStudent(g);
                    AddStudentCoursesFrame courseFrame = new AddStudentCoursesFrame(g,this);
                    courseFrame.setVisible(true);
                    setVisible(false);
                    labelAlert.setText(txtName.getText() + " " + txtSurname.getText() + " is added");
                    clear();
                }
            }
        }
    }//GEN-LAST:event_txtYearKeyPressed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddCourses;
    private javax.swing.JButton btnClose;
    private javax.swing.JCheckBox checkBoxTheory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel labelAlert;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtSurname;
    private javax.swing.JTextField txtYear;
    private javax.swing.JTextField txtYearOfAdmission;
    // End of variables declaration//GEN-END:variables
}
